Dev
Maraleks-java/LearningJava pull request #1
Opened 2021-02-10 14:12 UTC by Maraleks-java

For checking

2021-02-10 19:50 UTC, AntonMorokin requested changes

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/MainTest.java
> +public class MainTest {
Это вообще что, куда?

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +public class CalculatorThree {
У тебя есть разделение по пакетом. Не нужно обзывать классы номерами.

- [ ] Назвать класс по-человечески

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +            output.displayMessage(Messages.CONTINUE_OR_STOP.getMessageText());
Код нужно структурировать отступами, пустыми строками и так далее.

- [ ] Исправить форматирование.

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +    private static final int OUTPUTTING_THE_RESULT = 0;
Название переменной не соответствует применению.

- [ ] Переименовать.

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +        switch ((char) expression[1]) {
Если передали неизвестную команду, результат всегда будет 0.

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
> +        double number = 0;
Объявление можно перенести ближе к использованию.

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +                                expression[1] = (double) userCommand;
В чём вообще смысл хранить и данные, и действия в одной структуре?

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
> +        commandCode = (int)command;
Может в одну строку приводить?

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
> +import tasks.procedural.refactor.Calculator;
Сначала идут объявления стандартных неймспейсов. Потом сторонних, потом твоих.

- [ ] Отсортировать.

2021-02-10 19:50 UTC, AntonMorokin commented on src/tasks/oop/task3/view/output/Output.java
> +    public Output(){
Зачем пустой конструктор?

2021-02-10 19:52 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +                                expression[1] = (double) userCommand;
Кстати здесь ты приводишь char сразу к double, а ниже - с промежутком через int.

2021-02-11 08:17 UTC, Maraleks-java commented on src/tasks/oop/task3/view/output/Output.java
> +    public Output(){
Конструктор по соглашению, насколько я помню, всегда надо объявлять, пусть и пустой.

2021-02-11 08:19 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
> +        commandCode = (int)command;
Ты вроде говорил разделять этапы по строкам.

2021-02-11 08:21 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +                                expression[1] = (double) userCommand;
1. Не хотел плодить переменные.
2. Ок.

2021-02-11 08:23 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +        switch ((char) expression[1]) {
Так если передали неизвестную команду - вылетает исключение.

2021-02-11 08:23 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +    private static final int OUTPUTTING_THE_RESULT = 0;
Ок

2021-02-11 08:23 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +            output.displayMessage(Messages.CONTINUE_OR_STOP.getMessageText());
Ок

2021-02-11 08:26 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +public class CalculatorThree {
Ок

2021-02-11 08:27 UTC, Maraleks-java commented on src/tasks/MainTest.java
> +public class MainTest {
Ок

2021-03-04 13:14 UTC, Maraleks-java commented on src/tasks/MainTest.java
> +public class MainTest {
Исправлено

2021-03-04 13:14 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +public class CalculatorThree {
Исправлено

2021-03-04 13:18 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +            output.displayMessage(Messages.CONTINUE_OR_STOP.getMessageText());
Исправлено

2021-03-04 13:21 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +    private static final int OUTPUTTING_THE_RESULT = 0;
Исправлено

2021-03-04 13:27 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/CalculatorThree.java
> +        switch ((char) expression[1]) {
Записать неизвестную команду не выйдет. isMathCommand() решает этот вопрос.  Не вижу смысла править.

2021-03-04 13:28 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
> +        double number = 0;
Исправлено

2021-03-04 13:38 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
> +        commandCode = (int)command;
Исправлено.

2021-03-04 13:40 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
> +import tasks.procedural.refactor.Calculator;
У меня этого импорта нет сейчас почему-то.

2021-03-04 20:05 UTC, AntonMorokin requested changes

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +/**
Аннотации добавляются в начало файла.

- [x] Перенести в начало файла.

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +    /**
Что это?

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +    private final Input input;
Константы описываются рядом с константами, поля - рядом с полями.

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +            }
После блока всегда должна следовать пустая строка.

- [ ] Исправить форматирование.

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                                    getMessageText());
Зачем такой перенос?

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                            // Do something...
Возможно неожиданное/непредсказуемое поведение.
Аналогично с другими пустыми default.

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                result = getSumOfNumbers(expression[0], expression[2]);
Есть смысл делать метод ради одного действия?

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                result = getSumOfNumbers(expression[0], expression[2]);
Можно упростить.

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
> +     * @return Custom number.
Чем он кастомный?

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
>      public double readsCodeCommandFromKeyboard() throws IOException {
В методах используется повелительное наклонение глагола, потому что ты указываешь, что требуется сделать.

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/view/output/Output.java
> + * @author Alexandr Markov
Где-то дисклеймер есть, где-то - нет.
Почему так?

2021-03-04 20:05 UTC, AntonMorokin commented on src/tasks/oop/task3/view/output/Output.java
> +                ofPattern("yyyy.MM.dd hh:mm:ss"));
Странный перенос строки.

2021-03-04 20:13 UTC, AntonMorokin requested changes

2021-03-04 20:13 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +    public void start() throws IOException {
Метод не только стартует, но и продолжает, и заканчивает, и повторяет цикл.

- [ ] Переименовать.

2021-03-04 20:13 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                            break;
Основной метод получился огромным. При этом метки внутри свитча намекают, что надо бы выделить более мелкие методы.

2021-03-04 20:27 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +                                    getMessageText());
Check ругался

2021-03-04 20:48 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +/**
Исправлено

2021-03-04 20:54 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
> +     * @return Custom number.
Исправлено

2021-03-04 21:01 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +    /**
Если ты за 15-ю строку - doc чтобы не ругался check

2021-03-04 21:03 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +    private final Input input;
Исправлено.

2021-03-04 21:03 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +            }
Check ругался

2021-03-05 21:35 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +    /**
Исправлено.

2021-03-05 21:36 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +            }
Исправлено.

2021-03-05 21:43 UTC, Maraleks-java commented on src/tasks/oop/task3/view/output/Output.java
> +                ofPattern("yyyy.MM.dd hh:mm:ss"));
исправлено.

2021-03-06 08:04 UTC, AntonMorokin requested changes

2021-03-06 08:04 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +    /**
Если уж пишешь описание к членам, то делай его внятным. А не для того, чтобы анализатор замолчал.

2021-03-23 12:17 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
> +import tasks.procedural.refactor.Calculator;
Исправлено.

2021-03-23 12:18 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +                result = getSumOfNumbers(expression[0], expression[2]);
Исправлено.

2021-03-23 12:28 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
>      public double readsCodeCommandFromKeyboard() throws IOException {
Исправлено на readKeyboardCommandCode(). Второй метод по аналогии с первым.

2021-03-23 12:29 UTC, Maraleks-java commented on src/tasks/oop/task3/view/output/Output.java
> + * @author Alexandr Markov
Исправлено.

2021-03-23 12:30 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +                            break;
Исправлено. Возникла проблема с досрочным выходом из метода. Решаю.

2021-03-23 12:36 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +    public void start() throws IOException {
Исправлено.

2021-03-27 08:04 UTC, AntonMorokin requested changes

2021-03-27 08:04 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +     * The constant defines the current stage of the calculator operation.
Описание вообще не про эти четыре константы.

2021-03-27 08:04 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                if (stage == ENTER_FIRST_NUMBER || stage == ENTER_SECOND_NUMBER) {
Учитывая логику метода read number, можно упростить ветвление

2021-03-27 08:04 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +            case (PERFORM_CALCULATION):
Метод либо читает команду, либо выполняет расчёт. Но не всё вместе.

2021-03-27 08:04 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
> +    public double readOnlyNumbersFromKeyboard() throws IOException,
Так одно число или несколько?

2021-03-27 08:04 UTC, AntonMorokin commented on src/tasks/oop/task3/view/messages/Messages.java
> +     * The constant stores the message text corresponding to the name
Описания вообще мимо.

2021-03-27 08:08 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +            while (attemptCounter > -1) {
Странная логика. Если попыток не осталось, то обнуляем и начинаем сначала?

2021-03-27 20:44 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +            while (attemptCounter > -1) {
Если попыток не осталось - возвращаемся к первому циклу, где просим пользователя нажать Enter или ввести stop. Все верно.

2021-03-27 20:48 UTC, Maraleks-java commented on src/tasks/oop/task3/view/messages/Messages.java
> +     * The constant stores the message text corresponding to the name
Object with a text message. Исправил на это.

2021-03-27 20:50 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
> +    public double readOnlyNumbersFromKeyboard() throws IOException,
Исправлено

2021-03-27 20:52 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +            case (PERFORM_CALCULATION):
Исправлено

2021-03-27 20:57 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +                if (stage == ENTER_FIRST_NUMBER || stage == ENTER_SECOND_NUMBER) {
Сделано.

2021-03-27 21:05 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +     * The constant defines the current stage of the calculator operation.
Поправил.

2021-03-28 09:35 UTC, AntonMorokin requested changes

2021-03-28 09:35 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +     * The constant stores the calculation step in numerical representation
Which of steps?

2021-03-28 09:35 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                readNumber(stage);
Уверен? Можно и нужно сделать правильнее.

2021-03-28 09:35 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
> +    public double readOnlyNumbersFromKeyboard() throws IOException,
Есть ещё.

2021-03-28 09:35 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
> +    public double readKeyboardCommandCode() throws IOException {
Прочитать команду клавиатуры?

2021-03-28 09:35 UTC, AntonMorokin commented on src/tasks/oop/task3/view/messages/Messages.java
> +     * Object with a text message.
Тот факт, что это объект, все знают и без таких комментариев.
Нужно изменить комментарий таким образом, чтобы он выполнял свою задачу.

2021-03-28 09:35 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> + * %W% %E% Aleksandr Markov
Я всё-таки не понимаю. Почему здесь аннотация в начале файла, а в остальных местах - только у класса?

2021-03-28 20:38 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> + * %W% %E% Aleksandr Markov
https://github.com/Maraleks-java/LearningJava/pull/1/commits  Исправил согласно примеру.

2021-03-28 20:39 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> + * %W% %E% Aleksandr Markov
https://www.magnumblog.space/java/131-translating-java-code-conventions#java_source_file_example Исправил согласно примеру.

2021-03-28 20:43 UTC, Maraleks-java commented on src/tasks/oop/task3/view/messages/Messages.java
> +     * Object with a text message.
Поправил. Если и этот вариант не подходит - то даже не знаю...

2021-03-28 20:49 UTC, Maraleks-java commented on src/tasks/oop/task3/input/Input.java
> +    public double readKeyboardCommandCode() throws IOException {
Исправил

2021-03-28 21:11 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +                readNumber(stage);
Исправлено

2021-03-28 21:15 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +     * The constant stores the calculation step in numerical representation
Да блин, из названия понятно, что это за константа статическая. Вообще не знаю, что там можно написать еще.

2021-03-28 21:15 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +     * The constant stores the calculation step in numerical representation
Так же понятно, что она хранит, и в каком представлении.

2021-03-30 19:57 UTC, AntonMorokin requested changes

2021-03-30 19:57 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +     * The constant stores the calculation step in numerical representation
Описание либо пишется нормальным, либо не пишется вообще.

2021-03-30 19:57 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                            ENTER_SECOND_NUMBER.getMessageText());
Перенос отличается от 132й строки. Нужно выбрать один стиль в рамках метода.
Аналогично в других местах.

2021-03-30 19:57 UTC, AntonMorokin commented on src/tasks/oop/task3/view/output/Output.java
> +        // but does not have a body, the check asks to write a nested comment.
А зачем тогда этот конструктор?

2021-03-30 19:57 UTC, AntonMorokin commented on src/tasks/oop/task3/input/Input.java
> +    public double readOnlyNumbersFromKeyboard() throws IOException,
В описание исправил на number, в названии оставил numberS.

2021-03-30 19:57 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +        }
Пустая строка после блока.

2021-03-30 19:57 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +                    readCommand();
После команды всегда идёт ввод 2го числа. Можно добавить брейк и избежать проверки ниже.

2021-03-30 19:57 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +    private boolean startOver() {
Поскольку это не простой метод, а вычисляющий условие, ему нужно дать такое название, из которого будет сразу понятно назначение/возвращаемый тип. Обычно это делается глаголом необходимости, долженствования, возможности.
Кроме того, судя по описанию метод возвращает признак наличия попыток ввода. Что не указано в названии.
Лучше его переименовать, например, hasAttempts. Тогда while (hasAttempts()) читается как "пока есть попытки".
Тогда же становится понятно, что метод не просто проверяет наличие попыток, но ещё и обнуляет их. Что является сайд-эффектом, который вообще-то не ожидают.

2021-04-03 13:29 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +                    readCommand();
Исправил.

2021-04-03 13:31 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +        }
Исправил.

2021-04-03 16:25 UTC, Maraleks-java commented on src/tasks/oop/task3/view/output/Output.java
> +        // but does not have a body, the check asks to write a nested comment.
Исправлено.

2021-04-03 16:28 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +                            ENTER_SECOND_NUMBER.getMessageText());
Исправлено

2021-04-04 10:44 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +    private boolean startOver() {
Исправлено.

2021-04-04 16:56 UTC, AntonMorokin approved these changes

2021-04-04 16:56 UTC, AntonMorokin commented on src/tasks/oop/task3/calculator/Calculator.java
> +    /** Recorded expression */
Сомневаюсь

2021-04-04 17:13 UTC, Maraleks-java commented on src/tasks/oop/task3/calculator/Calculator.java
> +    /** Recorded expression */
В чем ? В оформлении комментария ?

2021-04-07 18:27 UTC, AntonMorokin approved these changes

2021-04-07 18:30 UTC, merged